# Generated by Django 5.1.5 on 2025-03-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.TextField(default='Ответ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender_name',
            field=models.CharField(default='Иванов', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(default='Новое', max_length=50),
        ),
    ]
